display/display.go
Side effects:
If the URL does not end in /, any ./ action will actually operate on the parent directory.
For example, if the current path is /a/b/c, ./d will go to /a/b/d.
This is expected in the RFC (as far as I can tell), but it's a potential "gotcha" in case of naive servers & co.
Fixes #71
=> ✨ Allow relative URLs in bottom bar

config/config.go, config/default.go, default-config.toml, display/private.go
A new config option that sets a command to open unsupported URL schemes (e.g. `gopher://`). It is unset by default to keep the previous behavior.
=> ✨Add option to open unknown URLs

display/display.go, display/help.go
The issues is that keypresses while the help is open are applied on the current document "underneath" the help table. This solution employs a similar technique that is used to ignore disallowed keypresses while a modal is open.
I also updated the help message to include help on page-up, page-down, u and d which were missing.
I also updated it to allow pressing enter to close the help too.
=> Fixes #55 - ignore navigation keypresses while help is open

config/config.go, display/display.go, display/newtab.go
The new tab page can now be loaded from `$XDG_CONFIG_HOME/amfora/new_tab.gmi`. This is documented in the default tab page. This implements what was suggested in issue #67 except for the ability to reload the new tab page, it is loaded once on startup.
- I didn't make the new tab file location configurable. It will require expanding `~` in the config option and possibly environment variables in order to honor `XDG_CONFIG_HOME` so I opted for a hardcoded path like the config file. If it is deemed necessary I can implement it.
- `config.ConfigDir` was exported to allow accessing `XDG_CONFIG_HOME` from outside `config`.
- I didn't implement the reload yet because it will require some special cases and I'm not sure where best to add them, `Reload()`, or `hasContent()` and `handleURL()`?
=> Custom new tab page

config/config.go, config/default.go, default-config.toml, renderer/renderer.go
Adds new boolean config option `ansi` in `[a-general]` to switch whether ANSI codes in page content will be rendered to terminal.
If `ansi `is set to false or `color` is set to false, any ANSI codes will be stripped from fetched content.
Fixes #79 
Here is a summary of results for the various values of the two options:
| config: color | config: ansi | Result                                    |
|---------------|--------------|-------------------------------------------|
| true          | true         | colorize headings & links; translate ANSI |
| true          | false        | colorize headings & links; strip ANSI     |
| false         | true         | no color; strip ANSI                      |
| false         | false        | no color; strip ANSI                      |
Notice how it is …
=> Strip ANSI codes from page based on config - fixes #79

display/display.go, display/help.go
One thing I found myself wanting to do from time to time is make a slight tweak to the URL I am currently viewing.
I added this feature to edit the URL of the current page. Press 'e' to have the bottomBar populate with the current URL in case you want to change the path or query param. It is a good way to go to a similar path or page based on the existing URL without having to type the whole thing out again.
=> Add 'e' keybinding feature to edit current URL

display/bookmarks.go
Hi! I decided I want to help contribute to this project when I have time, and I thought this would be a good issue to get started with -- #69
This isn't a perfect solution -- it just pulls from the cache right now if it's there. I can think of three solutions to this problem:
1. Persist the cache somehow on close / startup
2. Make gemini requests to grab favicons when opening bookmarks page, or on startup (seems slow, esp with many bookmarks)
3. Load icon only if it is already saved in the cache (my solution)
My solution is partway towards a solution based on 1. which seems to me like the best approach. What do you think?
Thanks for making this tool!
=> Emoji Favicons

webbrowser/open_browser_darwin.go, webbrowser/open_browser_other.go, webbrowser/open_browser_unix.go, webbrowser/open_browser_windows.go
* `webbrowser.Open` now tries to use `$BROWSER` env variable before giving up if there is no `xdg-open` installed.
* Do not check for `Xorg` program anymore. I think it is safe to expect that there is X installed if `$DISPLAY` is set.
* Add some comments.
As a comment in this PR mentions, I couldn't implement it. Something goes wrong when trying to restore `amfora` after closing a terminal browser (running in foreground, of course). If anyone wishes to implement it, they could check this:
* [termenv's screen.go](https://github.com/muesli/termenv/blob/master/screen.go) for altscreen sequences
* [this SO answer](https://stackoverflow.com/questions/21513321/how-to-start-vim-from-go) for information on how to launch ncurses programs
=> Implement a more robust algorithm for opening web links on unices

display/bookmarks.go
Apologies if I've missed some nuance that this breaks, but I figured it was more helpful to post a PR than an issue here.
This removes the protocol filter when adding a bookmark. I've been using amfora along with solderpunk's `agena` proxy (https://tildegit.org/solderpunk/agena) for accessing gopher, and it works beautifully well.
With this patch, adding and visiting bookmarks works just fine.
I'm happy to do further testing with my setup if necessary.
=> Remove protocol filter for bookmarking

config/config.go, go.mod, go.sum
=> XDG config

config/config.go
Basedir checks are not needed as it is set by default. See: https://github.com/rkoesters/xdg/blob/master/basedir/basedir.go#L52-L66
=> Remove basedir check

display/file.go, display/private.go, display/util.go
Simple implementation for rendering local (file://) documents.
When opening a `file://` url:
**If it is a directory:**
Render a page with links to all dirs and files in directory.
Links are made to all kinds of files, checking if reasonable to open is done when actually opening them (with error popups)
**If it is a file:**
- If not a gemini file, use mime.TypeByExtension to check if text/* otherwise bail
- render .gemini/.gmi as gemini
- else render as plaintext
fixes #103
=> fix for #103: Simple handling of local (file://) urls

contrib/themes/README.md, contrib/themes/one_dark.toml
Here's my port of [Atom One Dark](https://github.com/atom/atom/tree/master/packages/one-dark-syntax) theme.
On screenshots:
- OS: macOS Catalina
- terminal: [Alacritty](https://github.com/alacritty/alacritty)
- font: [JetBrains Mono](https://github.com/JetBrains/JetBrainsMono)
=> Add One Dark theme

README.md, config/config.go, config/default.go, config/default.sh, default-config.toml, display/download.go, sysopen/README.md, sysopen/open_browser_darwin.go, sysopen/open_browser_other.go, sysopen/open_browser_unix.go, sysopen/open_browser_windows.go
This is a partial solution to #121. It uses a slightly different configuration syntax than the one proposed. It looks like this:
``` TOML
[mime-handlers]
#
#
#
#
[mime-handlers."*/*"]
command = []
action = "prompt"
[mime-handlers."image/*"]
command = "display"
action = "open"
```
It leaves the mozz.us portal as the default, but it is trivial for a Linux user to add a `*/*` handler for `xdg-open`. On mac I think plain `open` works. I don't know about Windows though.
There are a handful of limitations with this implementation that I want to point out:
* Currently there is no piping/streaming. Files must be downloaded in full before opening
* Files are downloaded to the system temp dir (but this is configurable). They are never removed by amfora. I am relying on the system to clean the tmp …
=> Mediatypes support

display/display.go
When amforma is given a string to search, if that string contains a
valid protocol (gemini://), and that string contains trailing
whitespace, then the string is treated as a search term.
Although perhaps slightly more uncommon, if the input string was as a
result of copy/paste then it's possible the string could contain
trailing spaces, which is not what was intended, but rather should be
removed so that it's treated either as a valid gemini:// link or a
search term.
Some efforts around this appeared in #138
Note that with respect to #138, I wonder if there's still more work to be
done?  Currently, the following strings are considered valid search terms:
` abc`
`   gemini://xteddy.org`
At the moment, the check for this happens both in the form of a regexp, and
some other conditionals in …
=> search: trim trailing whitespace

display/help.go
This fixes the display issue when the `|` character is used as a keybinding #179 
I used literal tab characters in the help template. Since it is a raw string `\t` would not have worked.
Fixes #179
=> Made tab the delimiter for the help message table.

config/keybindings.go
`len(string)` returns bytes, not number of runes, so the "detect single character" clause breaks when passed a multibyte UTF-8 encoding.  Casting to `rune[]` causes it to count runes, and then we can correctly detect the "there is one character in the string" case.
Tested by setting up a multibyte key binding, and then using `tmux send-keys -t <pane-specifier>` to send key presses to amfora.  Looks like this fixes it entirely.
=> Fix issue 198

renderer/renderer.go
This should fix [this issue](https://github.com/makeworld-the-better-one/amfora/issues/234). I don't know whether this is the best way to do this (just copypasting the code except with *) but it seems to work.
=> fixed issue#234

display/bookmarks.go, display/display.go, display/download.go, display/handlers.go, display/private.go, display/subscriptions.go, display/tab.go, display/util.go
Hi, I've been using Amfora for short-while and wanted to contribute to this awesome project.  
**Proposed Changes:**  
- Extracted the about page check that is in `hasContent` to its own separate function as that was the only check prohibiting about page saves. Since a page's content has no implication on it being an about page, decoupling these checks seems like a good idea. But do let me know if this change does not make sense for the overall project, and I can look into other fixes.    
- Added a change to `downloadNameFromURL` so that when it's generating a filename for a saved about page, it uses the entire page url i.e. `about:subscriptions` as otherwise the filename was simply left blank.
Fixes #210 
P.S. I did not locate a contribution guide, so let me know if I went about …
=> Added ability to save `about:` pages.

amfora.go, logger/logger.go
Use an environment variable as a flag to easily switch on the amfora
debug logger without requiring a code change.
Sample usage
```
$ DEBUG=1 amfora
```
The rest of the logging behaviour has been preserved although I'm thinking of further improvements that could be made to it, such as structured logs for easier filtering and parsing by tools (e.g. JSON and jq), increase log coverage, etc.
=> Switch on debug logs via env var flag

amfora.go
Local files can now be loaded by relative path, rather than the
whole path preceded by the `file://` scheme indicator. It first
checks whether or not the requested URL has a scheme (by checking
for `://` in the URL). If not, it checks to see if the file exists
before opening. It also allows making intention known by
specifying `./` or `../` before the URL, closely matching the
behavior of Firefox.
This borrows code from @singalhimanshu's PR (#232).
Resolves #231
=> Allow opening local files by relative path

amfora.go, display/display.go, display/handlers.go, display/modals.go, display/private.go
Instead of about:newtab
it's less distracting than about:newtab imo, esp if the network is slow
=> When creating a tab with a URL, show a minimal interstitial page

display/bookmarks.go, display/display.go, display/download.go, display/help.go, display/modals.go, display/panels.go, display/subscriptions.go
Ignore any keypresses that don't have a corresponding binding in the Help page to avoid users triggering keybindings that remove the focus from the Help screen and becoming unable to exit, as Help keybindings are no longer captured correctly.
Rather than adding unnecessary complexity to make the Help page more flexible and capable of handling input events meant for other panels, I opted to restrict the input set to the keybindings that have a corresponding action in the Help page while it's active.
Closes #241 .
=> Fix users being unable to exit help menu

display/display.go
Caused by display.Error() being made to block for the loading page change.
We must call goURL / handleURL from a goroutine other than the main UI loop
I don't think there are any other problematic calls at the moment
Sorry :)
=> 🐛 Fix deadlock when an about: URL can't be loaded

display/display.go, display/handlers.go, display/modals.go, display/private.go, display/tab.go
Pushing commits to this branch, feel free to test / merge, or wait for more to come in.
=> Modal fixes (#281)

config/config.go
To get a new theme for Amfora, I went to the [theme page](https://github.com/makeworld-the-better-one/amfora/tree/master/contrib/themes), I downloaded one and I used the `include` key to import it. I want to use the `include` key because it feels way more convenient than copy-pasting a theme in the configuration file.
When the `include` directive was not under the `[theme]` tag, it was ignored, when the `include` key was under the `[theme]` tag, I got the following error:
```
Config error: invalid color format for "include": <My home folder>/.config/amfora/one_dark.toml
```
This PR make so that the theme parser ignores the `include` keys in order to prevent the error.
=> Fixed error when including theme.

display/bookmarks.go
Added basic top level 1 `#` heading extraction to suggest it as title for bookmark. I'm a regex newbie, but this was the best regex I could come up with that handled most cases that I tested for. Any regex wizardry advice is welcome. 
Closes #267
=> Add top level 1 heading as bookmark title suggestion

config/config.go, config/default.go, default-config.toml, display/handlers.go
This commit adds a confirmation prompt before following urls with
with certain schemes.
Wether or not a scheme requires confirmation can be configured in the
new `[url-promps]` section.
For #301
=> add confirmation prompts for url schemes

contrib/themes/README.md, contrib/themes/ayu_light.toml
My port of light variant of [Ayu theme](https://github.com/dempfi/ayu).
=> Add Ayu Light theme

display/display.go
Small logic change. Supports typing `localhost`, `localhost:port`, and `localhost/path/to/file` (and `localhost:port/path/to/file`).
Let me know if this is missing anything or if I messed something else up. thanks
=> localhost is direct URL now instead of geminispace.info/search?localhost (#326)

display/file.go
When viewing a local directory show index.gmi or index.gemini if one of
them exists instead of the generated directory listing. This allows
consistent browsing of local and remote gemini capsules.
=> Show local directory index file if available

client/url_test.go, config/config.go, config/default.go, default-config.toml, display/newtab.go
These changes update the URLs used for the official Project Gemini capsule[^1], including those used in the default config file and for new tabs.
Currently, in version `1.9.2`, the original URL[^2] presents the following page:
[^1]: Original news article: [2023-08-14 - Changing domain names](https://geminiprotocol.net/news/2023_08_14.gmi)
[^2]: `gemini://gemini.circumlunar.space`
=> Update URLs for official Project Gemini capsule

renderer/renderer.go
Using a color from the theme should make the rendering of text files be more in line with the colors chosen for styled content. Furthermore, allowing some form of user override for the color of plain text files allows users to individually fix bad color combinations. Such as in my case, where the combination of a solarized terminal theme and the default color chosen by amfora causes plain text files to be rendered as white text on an almost equally bright background.
=> Use preformatted_text color for rendering plain text files
